### PR TITLE
Predefined colorizer

### PR DESCRIPTION
**Pull request by BrianPeek**
Using this to start a discussion for using the predefined colorizers such that themes (dark/light/blue) and their color choices (Tools > Options > Environment > Fonts and Colors) work properly for 6502.  The color scheme currently in place is very hard to read in default dark theme.  Thoughts?

### CODE REVIEW

**Comment by OlivierGuinart** [comment]
Hi Brian,

I’m back home 😊. I had never tried the extension in other themes, especially dark, and while it it’s not looking that back IMO, I see your point about respecting user’s preferences. Let me try with your changes. Also, this looks like the same PR with more commits? I’ll probably inject your suggestions into master myself.

Thanks!

Olivier.

**Comment by BrianPeek** [comment]
Nope, different PR, the msgs at the stop were me merging the changes you committed to master back into this branch.  But it’s a new PR and new branch from my fork.

Give it a try and let me know what you think.  The selections I chose for some of the predefined types were a bit arbitrary as there isn't a 1:1 mapping for everything, so some tweaking may be required.

**Comment by OlivierGuinart** [comment]
Ah, you continued out of your branch, I get it now. I’ll try your selections first.

**Comment by OlivierGuinart** [comment]
FYI, I made small changes in the 3 files under https://github.com/OlivierGuinart/Merlin32Language/tree/BetterThemeColoringSupport/Coloring/Classification. Merlin32 are also now listed in “Fonts and Colors” settings, in case users want to customize these further than just the regular base coloring.

I’ll merge this branch within a week or so.

From: Olivier Guinart [mailto:olivier_guinart@live.com]
Sent: Saturday, October 7, 2017 5:27 PM
To: OlivierGuinart/Merlin32Language <reply@reply.github.com>; OlivierGuinart/Merlin32Language <Merlin32Language@noreply.github.com>
Cc: OlivierGuinart <olivier_guinart+github@live.com>; Comment <comment@noreply.github.com>
Subject: RE: [OlivierGuinart/Merlin32Language] Predefined colorizer (#5)

Ah, you continued out of your branch, I get it now. I’ll try your selections first.

**Comment by BrianPeek** [comment]
Even better, I'll give it a try tonight.  Thanks!

**Comment by BrianPeek** [comment]
This looks good to me.  I'm going to close this PR. Thanks!

**Pull request closed without merging**
